# Gradle
org.gradle.jvmargs=-Xmx2G -Duser.language=en -Duser.country=US
org.gradle.parallel=true

# Minecraft / Java
minecraft_version=26.3
minecraft_version_range=[26.3]

# Fabric Properties
loader_version=0.19.5
fabric_api_version=0.160.6+26.3
modmenu_version=21.0.0-beta.1

# Quilt Properties
quilt_loader_version=0.31.0-beta.4

# NeoForge Properties
neo_version=26.3.0.1-beta

# Shared Dependencies
cloth_config_version=26.3.158

# Mod Properties
mod_id=bettershulker
mod_name=Better Shulker Boxes
mod_license=MIT
mod_version=1.6.2
maven_group=com.bettershulker
archives_base_name=better-shulker-boxes
