modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Jom3a"
logoFile="icon.png"
description='''
Peek inside Shulker Boxes and Ender Chests without placing them. Better Shulker Boxes adds interactive full and compact previews with direct insert, extract, restock, deposit, themes, and resource-pack compatible GUI textures.
'''

[[mixins]]
config="bettershulker.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="cloth_config"
type="required"
versionRange="[${cloth_config_version},)"
ordering="NONE"
side="BOTH"
